const caesarstone20 = {
  standard: "RM 450/FR or RM 270/SF",
  deluxe: "RM 470/FR or RM 280/SF",
  premium: "RM 545/FR or RM 340/SF",
  supernatural: "RM 670/FR or RM 440/SF",
  supernaturalJumbo: "RM 800/FR or RM 500/SF",
  supernaturalPremium: "RM 1250/FR or RM 860/SF",
  supernaturalPremiumJumbo: "RM 1500/FR or RM 1010/SF",
  outdoor: "RM 625/FR or RM 440/SF",
};

const {
  standard,
  deluxe,
  premium,
  supernatural,
  supernaturalJumbo,
  supernaturalPremium,
  supernaturalPremiumJumbo,
  outdoor,
} = caesarstone20;

export const caesarstoneStandard = [
  {
    stoneName: "Snow",
    materialCode: "2141",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: standard,
    imgSrc: "/caesarstone/2141.jpg",
  },
  {
    stoneName: "Jet Black",
    materialCode: "3100",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: standard,
    imgSrc: "/caesarstone/3100.jpg",
  },
  {
    stoneName: "Oyster",
    materialCode: "4030",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: standard,
    imgSrc: "/caesarstone/4030.jpg",
  },
  {
    stoneName: "Clamshell",
    materialCode: "4130",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: standard,
    imgSrc: "/caesarstone/4130.jpg",
  },
  {
    stoneName: "Buttermilk",
    materialCode: "4220",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: standard,
    imgSrc: "/caesarstone/4220.jpg",
  },
  {
    stoneName: "Ginger",
    materialCode: "4330",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: standard,
    imgSrc: "/caesarstone/4330.jpg",
  },
  {
    stoneName: "Mink",
    materialCode: "4350",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: standard,
    imgSrc: "/caesarstone/4350.jpg",
  },
  {
    stoneName: "Intense White",
    materialCode: "6011",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: standard,
    imgSrc: "/caesarstone/6011.jpg",
  },
];

export const caesarstoneDeluxe = [
  {
    stoneName: "Fresh Concrete",
    materialCode: "4001",
    finish: "Concrete",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: deluxe,
    imgSrc: "/caesarstone/4001.jpg",
  },
  {
    stoneName: "Raven",
    materialCode: "4120",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: deluxe,
    imgSrc: "/caesarstone/4120.jpg",
  },
  {
    stoneName: "Shitake",
    materialCode: "4230",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: deluxe,
    imgSrc: "/caesarstone/4230.jpg",
  },
  {
    stoneName: "Organic White",
    materialCode: "4600",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: deluxe,
    imgSrc: "/caesarstone/4600.jpg",
  },
  {
    stoneName: "Frozen Terra",
    materialCode: "4601",
    finish: "Concrete",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: deluxe,
    imgSrc: "/caesarstone/4601.jpg",
  },
  {
    stoneName: "Georgian Bluffs",
    materialCode: "6134",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: deluxe,
    imgSrc: "/caesarstone/6134.jpg",
  },
];

export const caesarstonePremium = [
  {
    stoneName: "Pure White",
    materialCode: "1141",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: premium,
    imgSrc: "/caesarstone/1141.jpg",
  },
  {
    stoneName: "Alpine",
    materialCode: "5110",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: premium,
    imgSrc: "/caesarstone/5110.jpg",
  },
  {
    stoneName: "Bianco Drift",
    materialCode: "6131",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: premium,
    imgSrc: "/caesarstone/6131.jpg",
  },
];

export const caesarstoneSupernatural = [
  {
    stoneName: "Piatra Grey",
    materialCode: "5003",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: supernatural,
    imgSrc: "/caesarstone/5003.jpg",
  },
  {
    stoneName: "Vanilla Noir",
    materialCode: "5100",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: supernatural,
    imgSrc: "/caesarstone/5100.jpg",
  },
  {
    stoneName: "Atera Blanca",
    materialCode: "5112",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: supernatural,
    imgSrc: "/caesarstone/5112.jpg",
  },
  {
    stoneName: "Arabetto",
    materialCode: "5171",
    finish: "Polished",
    thickness: "20mm",
    slabSize: "3000x1400mm",
    price: supernatural,
    imgSrc: "/caesarstone/5171.jpg",
  },
  {
    stoneName: "Symphony Grey",
    materialCode: "5133",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: supernatural,
    imgSrc: "/caesarstone/5133.jpg",
  },
  {
    stoneName: "Frosty Carrina",
    materialCode: "5141",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: supernatural,
    imgSrc: "/caesarstone/5141.jpg",
  },
  {
    stoneName: "White Attica",
    materialCode: "5143",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: supernatural,
    imgSrc: "/caesarstone/5143.jpg",
  },
  {
    stoneName: "Moorland Fog",
    materialCode: "6046",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: supernatural,
    imgSrc: "/caesarstone/6046.jpg",
  },
  {
    stoneName: "Woodlands",
    materialCode: "6338",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: supernatural,
    imgSrc: "/caesarstone/6338.jpg",
  },
];

export const caesarstoneSupernaturalJumbo = [
  {
    stoneName: "Cloudburst Concrete",
    materialCode: "4011",
    finish: "Rough",
    thickness: "20mm",
    slabSize: "3300x1600mm",
    price: supernaturalJumbo,
    imgSrc: "/caesarstone/4011.jpg",
  },
  {
    stoneName: "Topus Concrete",
    materialCode: "4023",
    finish: "Rough",
    thickness: "20mm",
    slabSize: "3300x1600mm",
    price: supernaturalJumbo,
    imgSrc: "/caesarstone/4023.jpg",
  },
  {
    stoneName: "Rugged Concrete",
    materialCode: "4033",
    finish: "Rough",
    thickness: "20mm",
    slabSize: "3300x1600mm",
    price: supernaturalJumbo,
    imgSrc: "/caesarstone/4033.jpg",
  },
  {
    stoneName: "Airy Concrete",
    materialCode: "4044",
    finish: "Rough",
    thickness: "20mm",
    slabSize: "3300x1600mm",
    price: supernaturalJumbo,
    imgSrc: "/caesarstone/4044.jpg",
  },
  {
    stoneName: "Adamina",
    materialCode: "5222",
    finish: "Polished",
    thickness: "20mm",
    slabSize: "3300x1600mm",
    price: supernaturalJumbo,
    imgSrc: "/caesarstone/5222.jpg",
  },
  {
    stoneName: "Black Tempal",
    materialCode: "5810",
    finish: "Natural",
    thickness: "20mm",
    slabSize: "3300x1600mm",
    price: supernaturalJumbo,
    imgSrc: "/caesarstone/5810.jpg",
  },
];

export const caesarstoneSupernaturalPremium = [
  {
    stoneName: "Statuario Maximus",
    materialCode: "5031",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: supernaturalPremium,
    imgSrc: "/caesarstone/5031.jpg",
  },
  {
    stoneName: "Empira Black",
    materialCode: "5101",
    finish: "Polished",
    thickness: "20mm",
    slabSize: "3000x1400mm",
    price: supernaturalPremium,
    imgSrc: "/caesarstone/5101.jpg",
  },
  {
    stoneName: "Calacatta Nuvo",
    materialCode: "5131",
    finish: "Polished",
    thickness: "13/20mm",
    slabSize: "3000x1400mm",
    price: supernaturalPremium,
    imgSrc: "/caesarstone/5131.jpg",
  },
  {
    stoneName: "Calacatta Maximus",
    materialCode: "5114",
    finish: "Polished",
    thickness: "20mm",
    slabSize: "3000x1400mm",
    price: supernaturalPremium,
    imgSrc: "/caesarstone/5131.jpg",
  },
];

export const caesarstoneSupernaturalPremiumJumbo = [
  {
    stoneName: "Oxidian",
    materialCode: "4735",
    finish: "Natural",
    thickness: "20mm",
    slabSize: "3300x1600mm",
    price: supernaturalPremiumJumbo,
    imgSrc: "/caesarstone/4735.jpg",
  },
  {
    stoneName: "Empira White",
    materialCode: "5151",
    finish: "Polished",
    thickness: "20mm",
    slabSize: "3300x1600mm",
    price: supernaturalPremiumJumbo,
    imgSrc: "/caesarstone/5151.jpg",
  },
];

export const caesarstoneOutdoor = [
  {
    stoneName: "Midday",
    materialCode: "0405",
    finish: "Concrete",
    thickness: "20mm",
    slabSize: "3000x1400mm",
    price: outdoor,
    imgSrc: "/caesarstone/0405.jpg",
  },
  {
    stoneName: "Clear Skies",
    materialCode: "0406",
    finish: "Concrete",
    thickness: "20mm",
    slabSize: "3000x1400mm",
    price: outdoor,
    imgSrc: "/caesarstone/0406.jpg",
  },
  {
    stoneName: "Palm Shade",
    materialCode: "0515",
    finish: "Honed",
    thickness: "20mm",
    slabSize: "3000x1400mm",
    price: outdoor,
    imgSrc: "/caesarstone/0515.jpg",
  },
];
